# Generated by Django 5.0.6 on 2024-06-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_data',
            options={'verbose_name': 'User Data', 'verbose_name_plural': 'User Data'},
        ),
        migrations.AlterModelTable(
            name='user_data',
            table='user_data',
        ),
    ]
